export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Новая задача",
    date: "31.10.23",
    status: "Нужно сделать",
  },
  {
    id: 3,
    topic: "Research",
    title: "Копирайтинг",
    date: "01.11.23",
    status: "В работе",
  },
  {
    id: 4,
    topic: "Research",
    title: "Дизайн макета",
    date: "02.11.23",
    status: "Тестирование",
  },
  {
    id: 5,
    topic: "Research",
    title: "Исследование",
    date: "03.11.23",
    status: "Готово",
  },
  {
    id: 6,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 7,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 8,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 9,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 10,
    topic: "Copywriting",
    title: "Копирайтинг",
    date: "01.11.23",
    status: "В работе",
  },
  {
    id: 11,
    topic: "Web Design",
    title: "Копирайтинг",
    date: "01.11.23",
    status: "В работе",
  },
];